sudo: required
services:
  - docker

# build test containers
before_install:
  - docker build -t meir/react-test -f ./client/Dockerfile.dev ./client

# run tests
script:
  - docker run -e CI=true meir/react-test npm test

# if test succeseededd build prod versions
after_success:
  - docker build -t meir/multi-client  ./client
  - docker build -t meir/multi-nginx ./nginx
  - docker build -t meir/server ./server
  - docker build -t meir/worker ./worker

# login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# push images to docker hub 

  - docker push meir/multi-client
  - docker push meir/multi-nginx
  - docker push meir/multi-server
  - docker push meir/multi-worker

